// import AngularIcon from '../assets/icons/AngularIcon';
import HtmlIcon from '../assets/icons/HtmlIcon';
import JsIcon from '../assets/icons/jsICon';
import '../styles/components/SliderComponent.css'
import PhpIcon from './../assets/icons/PhpIcon';
import PythonIcon from './../assets/icons/PythonIcon';


function SliderComponent() {
  return (  
    <div>
      <div className="logos signal-container logos-app bg-pyellow">
        <div className="logos-slide">
          <h2 className="text-black">
            <JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon>
            <JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon>
            <JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon>
            <JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon>
            <JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon>
            <JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon>
            <JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon>
            <JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon>
            <JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon>
            <JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon>
            <JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon>
            <JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon>
            <JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon>
            <JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon>
            <JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon>
            <JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon>
            <JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon>
            <JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon>
            <JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon>
            <JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon><JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon>
            <JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon><JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon><JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon><JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon><JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon><JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon><JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon><JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon><JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon><JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon>
            <JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon><JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon><JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon><JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon><JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon><JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon>
            <JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon><JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon><JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon><JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon><JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon><JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon><JsIcon></JsIcon>
            <PhpIcon></PhpIcon>
            <PythonIcon></PythonIcon>
            <HtmlIcon></HtmlIcon>
            {/* <AngularIcon></AngularIcon> */}
          </h2>
        </div>
      </div>
    </div>
  );
}

export default SliderComponent;